### ISSUE TITLE
Username request failed due to flarum permissions

### ISSUE THREAD

**Issue by littlegolden** [askvortsov1/flarum-categories#1]
### 【Issue】
When the permission of View user list is set to "registered member", all tags cannot be fully loaded when not logged in.

### 【Screenshoot】
![image.png](https://i.loli.net/2020/03/21/jKs78hL6VYtpOMa.png)
![image.png](https://i.loli.net/2020/03/21/nR6fs18xam3Lql5.png)

**Comment by askvortsov1** [comment]
This should be fixed in v0.1.4, thanks!
