### ISSUE TITLE
Problems with markdown editor @ new version.

### ISSUE THREAD

**Issue by maddoglv** [askvortsov1/flarum-categories#16]
Looks like

"askvortsov/flarum-categories": "^2.1",

breaks

"flarum/markdown": "^0.1.0", 

im dancing around with this all day:

error in chrome console:
![image](https://user-images.githubusercontent.com/36969329/116562147-97b6b500-a90b-11eb-8ed7-af1fae26c796.png)

way to reproduce
1) install clean project: composer create-project flarum/flarum . --stability=beta
2) composer require askvortsov/flarum-categories --ignore-platform-reqs -W

then get to editor and try to write down smth and try adding some bold or other stuff and its broken

using php 7.3 and mariadb in docker.

**Comment by maddoglv** [comment]
Looks like I did fix it
do step **1** and **2**

then go to your composer file and revert all changes but (img)

![image](https://user-images.githubusercontent.com/36969329/116679139-d3f12080-a9b2-11eb-9b98-568c5745662d.png)

and run **composer update**

it seams to fix it still its hacky variant to do it.

**Comment by askvortsov1** [comment]
> then go to your composer file and revert all changes but (img)

How does it look before reverting changes?

**Comment by askvortsov1** [comment]
I'm having trouble replicating this locally following the steps you provided. 

>  try adding some bold or other stuff and its broken

Are you trying to do this via the buttons? If so, that's a core issue right now.

**Comment by maddoglv** [comment]
![image](https://user-images.githubusercontent.com/36969329/117105593-06ba6080-ad87-11eb-9b16-da20469769c2.png)
before reverting changes

it looks like the 

"askvortsov/flarum-categories": "^2.1",
replaces
"flarum/core": "^0.1.0",

@line 1 mybe that is some composer problem!

and rewerting just sets core back and its all good

**Comment by maddoglv** [comment]
just run composer update before adding extension that will do the trick.
