### ISSUE TITLE
[deleted] users will cause Categories to fail to load

### ISSUE THREAD

**Issue by littlegolden** [askvortsov1/flarum-categories#2]
###【Reproduce】
1. A user named Test creates a discussion under a label
2. The administrator deletes this user, and the user is now displayed as "[deleted]"
3. Click Categories. At this time, the label display is incomplete, and the console reports an error as shown in the figure.

### 【Screenshot】
![png](https://i.loli.net/2020/03/21/qZQV8Dv4eMbUSj9.png)

**Comment by askvortsov1** [comment]
This should be fixed in v0.1.4, thanks!
