### ISSUE TITLE
Tags sidebar glitches after accessing category view

### ISSUE THREAD

**Issue by Kakifrucht** [askvortsov1/flarum-categories#22]
When opening the category view and either selecting a category, or just going back whenever you select a main tag you will see a weird mix of different tags and subtags all appearing in the sidebar. Tested on multiple browsers, with full size desktop mode on and off.

**Comment by jslirola** [comment]
Hi, similar issue here. When I select a category from the index page I can see all subtags in a wrong place. Screenshots:

Tags settings:
![imagen](https://user-images.githubusercontent.com/6697559/134030236-d5ad47d3-a772-43cd-91f5-5926ec8141d7.png)

After selecting a category:
![imagen](https://user-images.githubusercontent.com/6697559/134030376-916690a0-3abb-4cc8-9a8c-6d5817316b96.png)

I thought it could be related with [this issue](https://github.com/flarum/core/issues/2943) so I applied the fix but it didn't work. Maybe I'm missing something.

**Comment by askvortsov1** [comment]
Just released v3.0.4, is that working now?

**Comment by jslirola** [comment]
Yes, thank you!
