### ISSUE TITLE
Categories will not get the latest tag information for a discussion.

### ISSUE THREAD

**Issue by littlegolden** [askvortsov1/flarum-categories#3]
【problem】
After the hashtag is changed, the position of the hashtag in the category will not change automatically.

And this issue  can be combined with #2 .

【video】
https://drive.google.com/open?id=1-xTohHoKye0FLDObyo5aNftlr7BDL0DJ

**Comment by askvortsov1** [comment]
I've done some investigating, and it looks like this is an issue with the Tags extension. I'll submit a PR there, the lastPostedDiscussion feature needs work anyway

**Comment by askvortsov1** [comment]
I'm keeping this open until the above PR is merged, but if you upgrade to v1.0.1, `php flarum tags:recalculate_stats` should provide a suitable temporary workaround.
