### ISSUE TITLE
Icon color of sub-category is the same as background circle's color, rendering the icon invisible

### ISSUE THREAD

**Issue by SKevo18** [askvortsov1/flarum-categories#41]
![image](https://user-images.githubusercontent.com/39010496/224558024-88723996-6ea4-4a6a-b851-ebcafc00e612.png)

As reported [here](https://discuss.flarum.org/d/7585/4156), this did not happen before v1.7.0. It seems to be happening because of this CSS:

https://github.com/askvortsov1/flarum-categories/blob/82e59be01d80f8d66883d7e453188c1436447354/js/src/forum/components/Category.tsx#L167

As you can see, the `color` property matches the background circle's `color` property:

https://github.com/askvortsov1/flarum-categories/blob/82e59be01d80f8d66883d7e453188c1436447354/js/src/forum/components/Category.tsx#L177

`this.tag.color()` should be the opposite of the background color.

**Comment by joseluisgilgil** [comment]
It is a pity that this happens, it detracts a lot from the presentation. Is it very complex to solve?

**Comment by Benzitczo** [comment]
Same my problem waiting no update???

@askvortsov1
