### ISSUE TITLE
Most icons from fontawesome are not displayed

### ISSUE THREAD

**Issue by Cwpute** [askvortsov1/flarum-categories#48]
I've tried adding several icons from fontawesome in my categories but i've found a pattern with most of them not working.

If the name is simple such as `book` or `question` it works as intended, no question asked.
However if it is an "unusual" icon such as a company logo like `facebook` or `bong` it only partially works and fetches something... that looks like an unrecognized character: 
![image](https://github.com/askvortsov1/flarum-categories/assets/80604512/0f7a14ff-d235-41af-a7a4-734fac570b2d)
But if it's an icon with a composed name like `person-digging` it will act as if it worked, but will show a blank space instead: 
![image](https://github.com/askvortsov1/flarum-categories/assets/80604512/49b89561-7a3f-4300-a713-aa38d96e35e5)
Now, i did find some composed icon names that would work, like `chess-queen` for example.

To me this seems like fontawesome is based on special characters and the way it is implemented is currently broken as some will work (they are essentially supported emojis) and some others won't.

Maybe this has to do with my old computer which i know have some problems with emojis, not recognizing the most recent for example.
It runs on 32bit Windows 8, which should give you a hint at its age.

**Comment by Yippy** [comment]
![image](https://github.com/askvortsov1/flarum-categories/assets/6518915/dcdb4dc1-3576-45cb-b27d-29e62b7a5663)

Facebook isn't written as `fas fa-facebook-f` it's `fab fa-facebook-f`

![image](https://github.com/askvortsov1/flarum-categories/assets/6518915/7b8ddad5-b13c-4f5e-92d8-9a47705a49b8)

Bong is available and working, on my flarum website.

[)Person Digging icon fontawesome](https://fontawesome.com/v5/search?q=person-digging&o=r
) is not available in the default Font Awesome version, I believe you have other font installed that is causing these issue for you.

**Comment by Cwpute** [comment]
Interesting.
Unfortunately i've moved away from both Flarum and my old computer, so this issue i probably won't be able to contribute to anymore :/ perhaps it should be marked as stale or something else.

Le 15 avril 2024 13:39:38 GMT+02:00, Yippy ***@***.***> a écrit :
