### ISSUE TITLE
Api /tags postCount parameter type is not clear

### ISSUE THREAD

**Issue by xkeyC** [askvortsov1/flarum-categories#5]
open siteurl/api/tags

data > tag > attributes > postCount

If postCount is 0, then it is an int, otherwise it is a String number. When I developed a client using a strongly typed language, I encountered a type conversion problem. I can use type inference to temporarily solve the problem, but I hope its type can be fixed .

**Comment by askvortsov1** [comment]
Fixed in v1.0.0, thanks for the report!
