### ISSUE TITLE
it shows the statistics incorrectly on the categories

### ISSUE THREAD

**Issue by ghost** [askvortsov1/flarum-categories#7]
While closing the plugin from the admin panel, the left horse gives an error message. And the plugin does not close without refreshing the page. While the plugin is open, it shows the statistics incorrectly on the categories page. No error log.

http://prntscr.com/skslx1

**Comment by askvortsov1** [comment]
comment count doesn't exist by default: you need to run the `php flarum tags:recalculate_stats` command to generate that. It should update itself from there, although rerunning that command regularly is still recommended.
